# Generated by Django 3.2.19 on 2023-06-02 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_numbe',
            new_name='phone_number',
        ),
    ]
